### ISSUE TITLE
Conditional Logic grouping

### ISSUE THREAD

**Issue by Imagica** [moomoo-agency/uni-woo-custom-product-options#1]
I'm trying to write some conditional logic that has two parts and requires some grouping. For example I need to calculate the square metres then add a calculation based on the perimeter, for a frame. When I try and create a formula which groups my calculations in order to calculate it correctly it fails. How do I group calculation in the formula. 

Such as: 
((value1 * value2) * price) + (((value1 * 2) + (value2 * 2)) * 20)

How do I group calculations?

**Comment by matenka-andrii** [comment]
I will show you simply example. 

We have two options http://joxi.ru/n2Ya9VOCoq1M62  {uni_cpo_value1} and {uni_cpo_value2}

Here is the main formula:  http://joxi.ru/ZrJY90pc9Y5J6A
(({uni_cpo_value1}*{uni_cpo_value2})*{uni_cpo_price})+((({uni_cpo_value1}*2)+({uni_cpo_value2}*2))*20)
Notice! I have removed all spaces from your formula! 

Result: http://joxi.ru/KAgoaXWi4pGRYA  
((5 * 2) * 10) + (((5 * 2) + (2 * 2)) * 20)
http://joxi.ru/l2ZR9QefwpYD62

**Comment by Imagica** [comment]
Perfect, all seems to be working for me now. Thanks
