### ISSUE TITLE
Decimal values beyond 1 decimal place invalid

### ISSUE THREAD

**Issue by Imagica** [moomoo-agency/uni-woo-custom-product-options#2]
When I create a measurement field in metres, if the user enters a value with more than 1 decimal place it says the value is invalid. My client makes custom glass so being able to enter accurate measurements with at least 3 decimal places is important. How can I increase the specificity of the decimal field to allow at least 3 decimal places?

**Comment by matenka-andrii** [comment]
I think you need to set "Step value" http://joxi.ru/Y2LY9Ekc9KW3yA If you need 3 decimal places set "Step value" to 0.001 4 - 0.0001 etc!

**Comment by Imagica** [comment]
Perfect, setting step value solved it. Thanks!
