### ISSUE TITLE
Problem with configure price calculation for curtains

### ISSUE THREAD

**Issue by Petrpw** [moomoo-agency/uni-woo-custom-product-options#7]
I have problem with congifuration to price calculation,
1. Customer must choice textile
2. Customer choice width and high (first calculation is curtain mb price x width 
Then if customer need we saw the textile 2xhighxprice sawing+widthx sawing price 
Then customer must choose what tape will have, tape price x width 
Next sawing tape x width price. The tape i very inportant, beacuse the measurment fron tape is 1;2 (when customer need 1meter curtain we need 2meter material textile)
Price calculation must calculation hight textile+sawing(pre high and width)+tape+ x sawing tape  
=

**Comment by mrpsiho** [comment]
Hi! This is not exactly an issue, actually. If you are looking for a paid configuration service - please, write to support email: support@moomoo.agency.
I close this task.
